from sqlalchemy.orm import Session

from app.models.snack import Snack


STARTER_SNACKS = [
    {
        "name": "Bagara Rice",
        "description": "Hyderabadi-style aromatic rice with mint, coriander, whole spices, and fried onions.",
        "price": 179,
        "prep_minutes": 10,
        "calories": 360,
        "category": "Hyderabadi",
        "accent": "#15803d",
        "ingredients": "Basmati rice,Mint,Coriander,Fried onion,Whole spices,Vegan,Medium spice",
        "allergens": "",
    },
    {
        "name": "Chicken Curry",
        "description": "Home-style chicken curry with onion-tomato masala, curry leaves, and warm spices.",
        "price": 249,
        "prep_minutes": 14,
        "calories": 420,
        "category": "Non Veg",
        "accent": "#b91c1c",
        "ingredients": "Chicken,Onion,Tomato,Ginger garlic,Curry leaf,High protein,Medium spice",
        "allergens": "",
    },
    {
        "name": "Masala Cloud Popcorn",
        "description": "Air-popped corn with curry leaf, lime, and a gentle chilli kick.",
        "price": 129,
        "prep_minutes": 5,
        "calories": 180,
        "category": "Crunch",
        "accent": "#f59e0b",
        "ingredients": "Corn,Curry leaf,Lime,Chilli,Vegetarian,Mild spice",
        "allergens": "",
    },
    {
        "name": "Protein Chikki Bites",
        "description": "Peanut, sesame, jaggery, and whey bites for steady afternoon energy.",
        "price": 179,
        "prep_minutes": 3,
        "calories": 220,
        "category": "Protein",
        "accent": "#2f855a",
        "ingredients": "Peanut,Sesame,Jaggery,Whey,Vegetarian,High protein",
        "allergens": "Peanut,Milk,Sesame",
    },
    {
        "name": "Fruit Chaat Cup",
        "description": "Seasonal fruit with roasted cumin, mint, and black salt.",
        "price": 149,
        "prep_minutes": 4,
        "calories": 140,
        "category": "Fresh",
        "accent": "#0ea5e9",
        "ingredients": "Seasonal fruit,Cumin,Mint,Black salt,Vegan,No onion garlic",
        "allergens": "",
    },
    {
        "name": "Cocoa Date Laddoo",
        "description": "Dates, cocoa, coconut, and almonds with no refined sugar.",
        "price": 159,
        "prep_minutes": 2,
        "calories": 190,
        "category": "Sweet",
        "accent": "#e11d48",
        "ingredients": "Dates,Cocoa,Coconut,Almonds,Vegetarian,No refined sugar",
        "allergens": "Tree nuts",
    },
    {
        "name": "Mini Idli Podi Box",
        "description": "Soft mini idlis tossed with ghee podi and served with coconut chutney.",
        "price": 139,
        "prep_minutes": 8,
        "calories": 260,
        "category": "South Indian",
        "accent": "#dc2626",
        "ingredients": "Rice,Urad dal,Ghee,Milagai podi,Coconut,Vegetarian,Medium spice",
        "allergens": "Milk,Coconut",
    },
    {
        "name": "Masala Dosa Roll",
        "description": "Crisp dosa wrap with potato masala, podi, and tomato chutney.",
        "price": 169,
        "prep_minutes": 10,
        "calories": 310,
        "category": "South Indian",
        "accent": "#ea580c",
        "ingredients": "Rice,Urad dal,Potato,Mustard seed,Tomato,Vegetarian,Medium spice",
        "allergens": "",
    },
    {
        "name": "Medu Vada Minis",
        "description": "Crunchy mini vadas with sambar dip and coconut chutney.",
        "price": 149,
        "prep_minutes": 9,
        "calories": 280,
        "category": "South Indian",
        "accent": "#b45309",
        "ingredients": "Urad dal,Pepper,Curry leaf,Sambar,Coconut,Vegetarian,Medium spice",
        "allergens": "Coconut",
    },
    {
        "name": "Curd Rice Comfort Cup",
        "description": "Cooling curd rice with pomegranate, ginger, curry leaf, and tempering.",
        "price": 129,
        "prep_minutes": 5,
        "calories": 210,
        "category": "South Indian",
        "accent": "#0891b2",
        "ingredients": "Rice,Curd,Pomegranate,Ginger,Curry leaf,Vegetarian,Low spice",
        "allergens": "Milk",
    },
    {
        "name": "Paneer Tikka Skewers",
        "description": "Smoky paneer cubes with peppers, onion, and mint chutney.",
        "price": 219,
        "prep_minutes": 12,
        "calories": 330,
        "category": "North Indian",
        "accent": "#db2777",
        "ingredients": "Paneer,Capsicum,Onion,Yogurt,Spices,Vegetarian,High protein",
        "allergens": "Milk",
    },
    {
        "name": "Rajma Rice Bowl",
        "description": "Punjabi rajma over steamed rice with onion salad and pickle.",
        "price": 189,
        "prep_minutes": 10,
        "calories": 390,
        "category": "North Indian",
        "accent": "#7c2d12",
        "ingredients": "Kidney beans,Rice,Tomato,Onion,Spices,Vegan,Medium spice",
        "allergens": "",
    },
    {
        "name": "Chole Kulcha Pocket",
        "description": "Soft kulcha stuffed with chole, pickled onion, and coriander chutney.",
        "price": 179,
        "prep_minutes": 9,
        "calories": 360,
        "category": "North Indian",
        "accent": "#92400e",
        "ingredients": "Chickpea,Kulcha,Onion,Coriander,Amchur,Vegetarian,Medium spice",
        "allergens": "Gluten",
    },
    {
        "name": "Aloo Paratha Dippers",
        "description": "Paratha strips with curd, pickle, and butter on the side.",
        "price": 159,
        "prep_minutes": 8,
        "calories": 340,
        "category": "North Indian",
        "accent": "#ca8a04",
        "ingredients": "Wheat,Potato,Curd,Butter,Pickle,Vegetarian,Mild spice",
        "allergens": "Gluten,Milk",
    },
    {
        "name": "Millet Upma Cup",
        "description": "Little millet upma with vegetables, peanuts, and lemon.",
        "price": 149,
        "prep_minutes": 7,
        "calories": 230,
        "category": "Healthy",
        "accent": "#16a34a",
        "ingredients": "Little millet,Carrot,Beans,Peanut,Lemon,Vegan,High fiber",
        "allergens": "Peanut",
    },
    {
        "name": "Sprouts Bhel Jar",
        "description": "Moong sprouts, puffed rice, chutneys, onion, tomato, and sev.",
        "price": 139,
        "prep_minutes": 4,
        "calories": 170,
        "category": "Healthy",
        "accent": "#059669",
        "ingredients": "Moong sprouts,Puffed rice,Tomato,Onion,Sev,Vegan,High protein",
        "allergens": "Gluten",
    },
    {
        "name": "Filter Coffee Shot",
        "description": "Strong South Indian filter coffee served hot with balanced sweetness.",
        "price": 89,
        "prep_minutes": 3,
        "calories": 90,
        "category": "Beverage",
        "accent": "#78350f",
        "ingredients": "Coffee,Milk,Sugar,Vegetarian",
        "allergens": "Milk",
    },
    {
        "name": "Masala Chai Flask",
        "description": "Fresh ginger-cardamom tea for a quick team break.",
        "price": 79,
        "prep_minutes": 4,
        "calories": 100,
        "category": "Beverage",
        "accent": "#a16207",
        "ingredients": "Tea,Milk,Ginger,Cardamom,Sugar,Vegetarian",
        "allergens": "Milk",
    },
]


def seed_snacks(db: Session) -> None:
    snacks_by_name = {snack.name: snack for snack in db.query(Snack).all()}

    for starter_snack in STARTER_SNACKS:
        snack = snacks_by_name.get(starter_snack["name"])
        if snack:
            for field, value in starter_snack.items():
                setattr(snack, field, value)
        else:
            db.add(Snack(**starter_snack))

    db.commit()
